---
# tasks file for common-packages
- name: "Update APT cache"
  apt:  update_cache=yes
        cache_valid_time=3600
  when: ansible_os_family == 'Debian'

- name: "Install common packages"
  apt:  name={{ item }}
        state=installed
  with_items:
    - zip
    - curl
    - git
  when: ansible_os_family == 'Debian'
