---
# tasks file for docker
- name: "Add Docker Project app key"
  apt_key:
        keyserver=hkp://p80.pool.sks-keyservers.net:80
        id=58118E89F3A912897C070ADBF76221572C52609D

- name: "Add Docker Project repository"
  apt_repository:
        repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'

- name: "Install Docker Engine"
  apt:  name=docker-engine={{ docker_engine_version }}-0~{{ ansible_distribution_release }}

- name: "Install Docker Compose requirements"
  apt:  name=python-pip

- name: "Install Docker Compose"
  pip:  name=docker-compose=={{ docker_compose_version }}

- name: "Configure Docker users"
  user: name={{ item }}
        append=yes
        groups=docker
  with_items: docker_users

- name: "Add Docker images"
  shell:
        docker pull {{ item }}
  register: result
  changed_when: "'Status: Image is up to date for {{ item }}' not in result.stdout"
  with_items: docker_images
