---
# tasks file for postgres
- name: Update
  apt:  update_cache=yes

- name: Generate needed locales
  locale_gen:
        name={{ pg_locale }}
        state=present

- name: Install PostgreSQL packages
  apt: name=postgresql
       state=present
  environment:
    LC_ALL: "{{ pg_locale }}"

- name: Install other PostgreSQL needed packages
  apt: name={{ item }}
       state=present
  with_items:
    - python-psycopg2
    - libpq-dev

- name:
  shell: pg_createcluster 9.3 main --start
  environment:
    LC_ALL: "{{ pg_locale }}"
