---
- name: Create {{ pg_db_name }} database
  sudo_user: postgres
  postgresql_db:
        name={{ pg_db_name }}

- name: Create {{ pg_db_user }} user for {{ db_name }}
  sudo_user: postgres
  postgresql_user:
        db={{ pg_db_name }}
        name={{ pg_db_user }}
        password={{ pg_db_pass }}
        priv=CONNECT

- name: Set default {{ pg_db_user }} privileges
  sudo_user: postgres
  postgresql_privs:
        database={{ pg_db_name }}
        state=present
        privs=ALL
        type=database
        roles={{ pg_db_user }}

- name: Configure {{ pg_db_user }} local authentication
  lineinfile:
        backup=yes
        dest=/etc/postgresql/9.3/main/pg_hba.conf
        insertbefore='^local\s+all\s+all\s+peer\s*$'
        regexp='local\s+all\s+{{ pg_db_user }}\s+'
        line='local all {{ pg_db_user }} md5'
  notify:
    - reload postgres

- name: Configure {{ pg_db_user }} remote authentication from {{ pg_remote_client }}
  lineinfile:
        backup=yes
        dest=/etc/postgresql/9.3/main/pg_hba.conf
        line='host all {{ pg_db_user }} {{ pg_remote_client }} md5'
  when: pg_remote_client is defined
  notify:
    - reload postgres
