---
- name: "Create {{ db_name }} database"
  become_user: postgres
  postgresql_db:
        name={{ db_name }}

- name: "Create {{ db_user }} user for {{ db_name }}"
  become_user: postgres
  postgresql_user:
        db={{ db_name }}
        name={{ db_user }}
        password={{ db_pass }}
        priv=CONNECT

- name: "Set default {{ db_user }} privileges"
  become_user: postgres
  postgresql_privs:
        database={{ db_name }}
        state=present
        privs=ALL
        type=database
        roles={{ db_user }}

- name: "Configure {{ db_user }} local authentication"
  lineinfile:
        backup=yes
        dest=/etc/postgresql/9.3/main/pg_hba.conf
        insertbefore='^local\s+all\s+all\s+peer\s*$'
        regexp='local\s+{{ db_name }}\s+{{ db_user }}\s+'
        line='local {{ db_name }} {{ db_user }} md5'
  notify:
    - reload postgres

- name: "Configure listen addresses"
  lineinfile:
        backup=yes
        dest=/etc/postgresql/9.3/main/postgresql.conf
        regexp='^#?listen_addresses ='
        line="listen_addresses = '*'"
  when: db_remote_clients is defined
  notify:
    - restart postgres

- name: "Configure {{ db_user }} remote authentication from {{ db_remote_clients }} hosts"
  lineinfile:
        backup=yes
        dest=/etc/postgresql/9.3/main/pg_hba.conf
        line='host {{ db_name}} {{ db_user }} {{ db_remote_clients }} md5'
  when: db_remote_clients is defined
  notify:
    - reload postgres
