---
# tasks file for mysql
- name: "Update APT chache"
  apt:  update_cache=yes
        cache_valid_time=3600

- name: "Install MySQL server packages"
  apt:  name=mysql-server
        state=present

- name: "Install other MySQL needed packages"
  apt:  name={{ item }}
        state=present
  with_items:
    - python-mysqldb
