---
# tasks file for java-vm
#- name: "Add webupd8 Apt key"
#  apt_key:
#        id={{ webupd8_apt_key }}
#        keyserver=keyserver.ubuntu.com

- name: "Add the webupd8 APT repository"
  apt_repository:
        repo={{ webupd8_ppa }}
  register: webupd8_ppa

- name: "Auto accept Oracle license"
  command:
        sh -c 'echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections'
  changed_when: false

- name: "Install Java Oracle {{ version }} packages"
  apt:  name=oracle-java{{ version }}-installer

- name: "Set Java Oracle {{ version }} as default"
  apt:  name=oracle-java{{ version }}-set-default
  when: set_default
