---
# tasks file for common-users
- name: "Create {{ admins_group }} group"
  group:
        name={{ admins_group }}

- name: "Set {{ admins_group }} sudo configuration"
  template:
        src=sudo_admins.j2
        dest={{ admins_sudoers_file }}
        mode=440
        validate='visudo -cf %s'

- name: "Create default users"
  user: name={{ item.name }}
        group={{ item.group }}
        {% if item.shell is defined %}shell={{ item.shell }}{% else %}shell={{ default_shell }}{% endif %}
        comment="{{ item.full_name}}"
  with_items: current_users
  when: current_users is defined

- name: "Set SSH key authentication for default users"
  authorized_key:
        user={{ item.name }}
        key="{{ lookup('file', 'keys/id_rsa.' + item.name + '.pub')}}"
        exclusive=yes
  with_items: current_users
  when: current_users is defined

- name: "Delete users"
  user: name={{ item.name }}
        state=absent
        remove=yes
  with_items: deleted_users
  when: deleted_users is defined

